### ISSUE TITLE
[Bug] Mangadex deeplink bugs

### ISSUE THREAD

**Issue by joseph619** [jobobby04/TachiyomiSY#127]
## Bug 1: Mangadex homepage has option to be opened in TachiyomiSy

Steps to reproduce
1. Visit Mangadex homepage on Browser
2. Open in TachiyomiSy

Gives the following error:

> Could not open this manga:
> Unknown manga type for manga: https://mangadex.org

There shouldn't be an option to open Mangadex homepage, just manga info and chapters.

## Bug 2: Actual chapter doesn't open app

Steps to reproduce
1. Open a manga chapter on Mangadex from browser
2. Open in TachiyomiSy

Gives the following error

> Could not open this manga:
> Unknown manga type for manga: https://mangadex.org/chapter/1058681/1

**Comment by jobobby04** [comment]
Fixed in https://github.com/jobobby04/TachiyomiSY/commit/105302aa7b736919463e7e7f91c0d9fd2c9dcd46

**Comment by joseph619** [comment]
Bug 2 is still present (although I didn't know it shouldn't be visible in the first place)

**Comment by jobobby04** [comment]
Closed in favor of https://github.com/jobobby04/TachiyomiSY/issues/178
