### ISSUE TITLE
ExHentai no results found

### ISSUE THREAD

**Issue by patros36** [jobobby04/TachiyomiSY#1327]
### Steps to reproduce

Open Exhentai source.

### Expected behavior

See the Latest and Popular mangas

### Actual behavior

No result found on both.
![Screenshot_2024-11-19-03-22-19-52_a603e4da04bada03cae438f177815547](https://github.com/user-attachments/assets/53f6fcec-3b4d-40ce-817a-3b91c28117b5)

### TachiyomiSY version

1.11.0

### Android version

Android 13

### Device

OnePlus Nord2 5g

### Other details

Opening ExHentai source showd "No results found", but opening it in webview shows the site without problems.
Same with any ExHentai manga i have saved, it shows a nullPointer when i open it, no page can be opened, but it works fine in webview.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.11.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Exhentai seems to have invalidated cookies for a bunch of accounts, you will need to disable Exhentai and Enable Exhentai to login again. It should be fixed after that.

**Comment by Rit76Horizon** [comment]
> Exhentai seems to have invalidated cookies for a bunch of accounts, you will need to disable Exhentai and Enable Exhentai to login again. It should be fixed after that.

I'm having the same issue as above and Disable/Enable did not fix it.

**Comment by jobobby04** [comment]
Logout and go to advanced settings in TachiSY and click clear cookies

**Comment by Rit76Horizon** [comment]
> Logout and go to advanced settings in TachiSY and click clear cookies

I have no option to logout, clearing cookies does make it so that it's just a white screen when checked in web view, opening in browser shows the site.

**Comment by jobobby04** [comment]
By logout I meant disable Exhentai

**Comment by Rit76Horizon** [comment]
> By logout I meant disable Exhentai

I disabled Exhentai when I cleared cookies. But the results are still the same.

**Comment by jobobby04** [comment]
If you are using a custom Igneous cookie it may be invalid now. Otherwise you will need to find out how to get a new valid one. VPNs sometimes work as long as you connect to a non-shadowbanned country.
I've confirmed that everything in SY works. You are just encountering one of the issues with Exhentai itself.

**Comment by Rit76Horizon** [comment]
> If you are using a custom Igneous cookie it may be invalid now. Otherwise you will need to find out how to get a new valid one. VPNs sometimes work as long as you connect to a non-shadowbanned country. I've confirmed that everything in SY works. You are just encountering one of the issues with Exhentai itself.

Exhentai works just fine in my browser, It is exclusively through that App that I am unable to access. When in webview after clearing cookies it is just a white screen, and opening in browser with the dropdown in webview shows the site as normal. I do not know how to give TachiyomiSY a new cookie for Exhentai.

**Comment by patros36** [comment]
For me disabling and enabling fixed it, thanks 👌
