### ISSUE TITLE
crash on extension installation using shizuku

### ISSUE THREAD

**Issue by AminurAlam** [jobobby04/TachiyomiSY#1454]
### Steps to reproduce

1. turn on shizuku installer
2. try to install/update an extension

### Expected behavior

no crash should occur

### Actual behavior

the extension downloads and then it takes around 5~10 seconds before showing the crash screen

the extension appears to be successfuly installed when you restart the app

### Crash logs

crash when installing:
[fresh install.txt](https://github.com/user-attachments/files/20261944/fresh.install.txt)

theres another crash happening when shizuku is not running:

[shizuku not running.txt](https://github.com/user-attachments/files/20261955/shizuku.not.running.txt)

### TachiyomiSY version

preview r582

### Android version

Android 14

### Device

Samsung

### Other details

probably realed issue #1296 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] I have updated the app to version **[1.12.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [x] I have filled out all of the requested information in this form, including specific version numbers.
- [x] I understand that **Mihon does not have or fix any extensions**, and I **will not receive help** for any issues related to sources or extensions.

**Comment by NGB-Was-Taken** [comment]
Shizuku needs a version bump. 
This bug affects android version < 8 was fixed in 13.1.1. We are using 13.1.0, while the latest is 13.1.5. 
@jobobby04 mentioning you as it doesn't seem worth it to create a PR for this

**Comment by molitar** [comment]
I updated my Shizuku and still have a crash is there anything else we have to do in Tachiyomi?

**Comment by NGB-Was-Taken** [comment]
It has to be fixed in code.

**Comment by molitar** [comment]
Same problem Mihon does not crash with Shizuku

Steps to reproduce

Install any extension with Shizuku installer enabled application crash. Works fine in Mihon. I have included crash log below and this is after a fresh install and restore of data.
Expected behavior

Application should not crash
Actual behavior

application crashes
Crash logs

App ID: eu.kanade.tachiyomi.sy
App version: 1.12.0 (standard, https://github.com/jobobby04/TachiyomiSY/commit/5074e68b9cda0b90433dda490417fe80085374eb, 75, 2025-05-25T00:47:35Z)
Preview build: 583
Android version: 16 (SDK 36; build BP3A.250905.014)
Device brand: google
Device manufacturer: Google
Device name: felix (felix)
Device model: Pixel Fold
WebView: Android System WebView 140.0.7339.207
Current time: 2025-10-05T16:35:36.721-04:00

java.lang.Throwable: java.lang.RuntimeException: Unable to stop service eu.kanade.tachiyomi.extension.util.ExtensionInstallService@216a8af
at android.app.ActivityThread.handleStopService(ActivityThread.java:5559)
at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2668)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.dispatchMessage(Looper.java:315)
at android.os.Looper.loopOnce(Looper.java:251)
at android.os.Looper.loop(Looper.java:349)
at android.app.ActivityThread.main(ActivityThread.java:9041)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
Caused by: java.lang.UnsupportedOperationException
at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1212)
at j$.util.Collection$-CC.$default$removeIf(SourceFile:546)
at j$.util.Collection$-EL.removeIf(Unknown Source:11)
at eu.kanade.tachiyomi.extension.installer.ShizukuInstaller.onDestroy(SourceFile:11)
at eu.kanade.tachiyomi.extension.util.ExtensionInstallService.onDestroy(SourceFile:5)
at android.app.ActivityThread.handleStopService(ActivityThread.java:5541)
... 10 more

--------- beginning of crash
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: FATAL EXCEPTION: main
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 28797
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: java.lang.UnsupportedOperationException
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1212)
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: at j$.util.Collection$-CC.$default$removeIf(SourceFile:546)
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: at j$.util.Collection$-EL.removeIf(Unknown Source:11)
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: at eu.kanade.tachiyomi.extension.installer.ShizukuInstaller$shizukuPermissionListener$1.onRequestPermissionResult(SourceFile:29)
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: at rikka.shizuku.Shizuku$$ExternalSyntheticLambda4.run(SourceFile:11)
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:1041)
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:103)
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: at android.os.Looper.dispatchMessage(Looper.java:315)
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:251)
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: at android.os.Looper.loop(Looper.java:349)
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:9041)
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
2025-10-05 16:15:37.615 -0400 28797 28797 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
--------- beginning of main
2025-10-05 16:35:22.480 -0400 3641 3641 E DecorView[]: Destroying unexpected ActionMode instance of TYPE_FLOATING; com.android.internal.view.FloatingActionMode@94691c4 was not the current floating action mode! Expected null
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: FATAL EXCEPTION: main
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 3641
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: java.lang.RuntimeException: Unable to stop service eu.kanade.tachiyomi.extension.util.ExtensionInstallService@216a8af
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at android.app.ActivityThread.handleStopService(ActivityThread.java:5559)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2668)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:110)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at android.os.Looper.dispatchMessage(Looper.java:315)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:251)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at android.os.Looper.loop(Looper.java:349)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:9041)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1212)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at j$.util.Collection$-CC.$default$removeIf(SourceFile:546)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at j$.util.Collection$-EL.removeIf(Unknown Source:11)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at eu.kanade.tachiyomi.extension.installer.ShizukuInstaller.onDestroy(SourceFile:11)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at eu.kanade.tachiyomi.extension.util.ExtensionInstallService.onDestroy(SourceFile:5)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: at android.app.ActivityThread.handleStopService(ActivityThread.java:5541)
2025-10-05 16:35:26.215 -0400 3641 3641 E AndroidRuntime: ... 10 more
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: java.lang.RuntimeException: Unable to stop service eu.kanade.tachiyomi.extension.util.ExtensionInstallService@216a8af
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at android.app.ActivityThread.handleStopService(ActivityThread.java:5559)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2668)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at android.os.Handler.dispatchMessage(Handler.java:110)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at android.os.Looper.dispatchMessage(Looper.java:315)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at android.os.Looper.loopOnce(Looper.java:251)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at android.os.Looper.loop(Looper.java:349)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at android.app.ActivityThread.main(ActivityThread.java:9041)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at java.lang.reflect.Method.invoke(Native Method)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: Caused by: java.lang.UnsupportedOperationException
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1212)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at j$.util.Collection$-CC.$default$removeIf(SourceFile:546)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at j$.util.Collection$-EL.removeIf(Unknown Source:11)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at eu.kanade.tachiyomi.extension.installer.ShizukuInstaller.onDestroy(SourceFile:11)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at eu.kanade.tachiyomi.extension.util.ExtensionInstallService.onDestroy(SourceFile:5)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: at android.app.ActivityThread.handleStopService(ActivityThread.java:5541)
2025-10-05 16:35:26.218 -0400 3641 3641 E GlobalExceptionHandler: ... 10 more
2025-10-05 16:35:26.522 -0400 12812 12812 E y:error_handler: Not starting debugger since process cannot load the jdwp agent.
2025-10-05 16:35:26.633 -0400 12812 12812 E FeatureFlagsImplExport: android.os.flagging.AconfigStorageReadException: ERROR_PACKAGE_NOT_FOUND: package com.android.org.conscrypt.net.flags cannot be found on the device
2025-10-05 16:35:26.663 -0400 12841 12841 E de.tachiyomi.sy: Not starting debugger since process cannot load the jdwp agent.
2025-10-05 16:35:26.683 -0400 12812 12862 E ashmem : Pinning is deprecated since Android Q. Please use trim or other methods.
2025-10-05 16:35:26.715 -0400 12812 12883 E y:error_handler: No package ID 6a found for resource ID 0x6a0b000f.
2025-10-05 16:35:26.715 -0400 12812 12874 E SQLiteLog: (283) recovered 771 frames from WAL file /data/data/eu.kanade.tachiyomi.sy/databases/tachiyomi.db-wal
2025-10-05 16:35:26.929 -0400 12841 12841 E FeatureFlagsImplExport: android.os.flagging.AconfigStorageReadException: ERROR_PACKAGE_NOT_FOUND: package com.android.org.conscrypt.net.flags cannot be found on the device
2025-10-05 16:35:26.984 -0400 12841 12925 E ashmem : Pinning is deprecated since Android Q. Please use trim or other methods.
2025-10-05 16:35:27.231 -0400 12841 12944 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
2025-10-05 16:35:27.327 -0400 12841 12947 E de.tachiyomi.sy: No package ID 6a found for resource ID 0x6a0b000f.
TachiyomiSY version

r538
Android version

Android 16
Device

Google Pixel Fold

**Comment by jobobby04** [comment]
Fixed with shizuku bump in mihon
