### ISSUE TITLE
[Bug] App crashes on last page of chapter

### ISSUE THREAD

**Issue by jopejoe1** [jobobby04/TachiyomiSY#185]
## Device information
App version: 1.4.1 (standard, 4b3d92a05, 12)
Preview build: 319
Android version: 10 (SDK 29) 
Android build ID: QP1A.190711.020.G975FXXS9DTI8
Device brand: samsung
Device manufacturer: samsung
Device name: beyond2
Device model: SM-G975F
Device product name: beyond2ltexx

## Steps to reproduce
1. Open Chapter
2. Go to last page

### Expected behavior
Nothing

### Actual behavior
 Chrashes

## Other details
Chapters are dowloaded to the device.
Happens not with all Chapters
Seems like it does not happed with chapters recently downloaded

**Comment by scb261** [comment]
probably this https://github.com/tachiyomiorg/tachiyomi/commit/3df98d576ebfc183a50b6c458f655a8d272c4b7a

**Comment by jopejoe1** [comment]
Not sure if its related but clicking on the add tracking button for MAL also crashes the app

**Comment by ardittristan** [comment]
It also happens for non-downloaded chapters for me on prev 319

**Comment by acestars** [comment]
IMO it related to MAL crashes the app, maybe after last page the app try to sync with MAL. How about manga that has not synced with MAL, is it still crash?
[Log_2021-01-03_04-39-46.txt](https://github.com/jobobby04/TachiyomiSY/files/5760980/Log_2021-01-03_04-39-46.txt)

**Comment by jobobby04** [comment]
Fixed in the latest build

**Comment by jopejoe1** [comment]
Updated to preview 322 and its still crashing. 
And yes mangas with out mal link are not crashing so ot seems like ot has something to do with mal.

**Comment by joseph619** [comment]
try on Tachiyomi main app preview

**Comment by jopejoe1** [comment]
Works fine in main app preview.

**Comment by acestars** [comment]
could you explain to me what do you mean with "main app preview"?

**Comment by jopejoe1** [comment]
The preview version of the standard tachiyomi app and not the sy fork.
