### ISSUE TITLE
Bookmarks changing chapter to unread

### ISSUE THREAD

**Issue by DatHypnoboi** [jobobby04/TachiyomiSY#467]
### Steps to reproduce

1. Read chapter from updates tab
2. After closing reader, quickly bookmark read chapter before chapter is changed to read

### Expected behavior

The chapter should be bookmarked, but is still marked as read

### Actual behavior

Chapter is bookmarked as usual, but stays as unread

### Tachiyomi version

1.7.0

### Android version

Android 12

### Device

Google Pixel 3a

### Other details

Seems to be caused by chapter "status" still being considered as unread when it is bookmarked, giving it a "status" of unread and bookmarked, and preventing it from being updated to read properly, though this is just my assumption from what I have seen. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Try on the preview

**Comment by DatHypnoboi** [comment]
I tried on the preview as well. I've also figured out that it happens specifically when you bookmark the chapter before it changes to read

**Comment by jobobby04** [comment]
Probably addressed by https://github.com/jobobby04/TachiyomiSY/commit/992679e470843a2fd1539dc44b96db133565d442

**Comment by DatHypnoboi** [comment]
I can still reproduce the bug easily on the newest preview, though it is a bit tighter timing. Might be related to worse phone performance
