### ISSUE TITLE
download notification doesn't show up

### ISSUE THREAD

**Issue by Turhvjbufv** [jobobby04/TachiyomiSY#859]
### Steps to reproduce

Pause a download 

In the new release 1.9.3 when you pause the download notification it switchea and shows up cancel and continue button but in the new preview r508 it doesn't happen

### Expected behavior

Notification shows up with cancel and continue options 

### Actual behavior

No notification shows up
And you have to go to the download section in app in order to continue or cancel downloads 

### Tachiyomi version

App version: 1.9.1 preview 508

### Android version

Android 12

### Device

Samsung s10

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Probably fixed in the recent builds, either that or you disabled the notification

**Comment by Turhvjbufv** [comment]
> Probably fixed in the recent builds, either that or you disabled the notification

I'm on r508 I even uninstalled and reinstalled the app and the issue persist

![Screenshot.png](https://user-images.githubusercontent.com/91851160/236650309-ee5a3915-c459-40bc-89ef-d51e0f52a409.png)

https://user-images.githubusercontent.com/91851160/236650655-f073a037-9aee-4318-8000-a54e2efd46d7.mp4

**Comment by Turhvjbufv** [comment]
@jobobby04 
sorry for the tagging I just don't know if you're subscribed this post

**Comment by jobobby04** [comment]
Does it happen in the latest build(build 512?)

**Comment by Turhvjbufv** [comment]
Yes, although the recording was on 508 the same thing happens on r512

**Comment by Turhvjbufv** [comment]
Idk if this helps but on 1.9.3 it works



https://user-images.githubusercontent.com/91851160/236686291-197258ea-0aa4-472f-b01f-82bd873449db.mp4
